### PR TITLE
Define configuration

### PR DESCRIPTION
**Pull request by michaljurecko**
Jira: https://keboola.atlassian.net/browse/COM-471

Changes:
- Added README
- Added configuration definition.
- Installed NPM (NodeJs package manager) and ignored `node_modules` dir.

Based on these changes, the next step is to implement `testConnection`.

### CODE REVIEW

**Comment by michaljurecko** [comment]
@ondrajodas mal by si prosim cas na review? Jedna sa iba o konfiguraciu + testy, nemalo by to byt na dlho.

**Comment by ondrajodas** [comment]
zkusím to navečer nebo ráno :)

**Comment by michaljurecko** [comment]
@ondrajodas ahoj, dostanes sa k tomu, alebo si mam niekoho zohnat?

**Comment by ondrajodas** [comment]
@webrouse jdu na to

**Review by ondrajodas — APPROVED** [review]
LGTM 👍

**Pull request merged**
